[terminal.shell]
program = "C:\\Users\\ifreas\\opt\\PowerShell-7.5.4-win-x64\\pwsh.exe"
args = ["-NoLogo"]

[font]
size = 12

[font.normal]
family = "CaskaydiaMono Nerd Font"
style = "Regular"

[font.bold]
family = "CaskaydiaMono Nerd Font"
style = "Bold"

[font.italic]
family = "CaskaydiaMono Nerd Font"
style = "Italic"
